export interface WizardAnswers {
  projectName: string;
  description: string;
  language: "English" | "Polish";
  audience: string;
  stack: string;
  tddTier: "none" | "basic" | "full";
  deployment: string;
  tools: string[];
  hooksScope: "project" | "global" | "both" | "skip";
}

const today = () => new Date().toISOString().split("T")[0];

const TDD_RULE: Record<WizardAnswers["tddTier"], string> = {
  none: "No tests required at this stage. Move fast, prove the concept.",
  basic: "Basic TDD: every new function ships with at least one happy-path test before the feature is marked done.",
  full: "Full TDD: failing test first (RED) → minimal implementation (GREEN) → refactor. Coverage ≥ 80 %. Never skip RED.",
};

const TDD_LABEL: Record<WizardAnswers["tddTier"], string> = {
  none: "No tests",
  basic: "Basic TDD",
  full: "Full TDD (≥ 80 % coverage)",
};

function state(a: WizardAnswers): string {
  return `# Project state

> **Status as of ${today()}** — generated by vibe-forge Setup Wizard v1.0

## What this is
${a.description}

## Stack
${a.stack}

## Phase
0 — project initialized. Setup Wizard complete, development not yet started.

## Active work
None yet.

## Known issues
None.

## Next steps
1. Open this project in your AI tool of choice.
2. Read \`PROJECT_MAP.md\` to orient the agent.
3. Use \`/atomic-prompts\` to generate your first feature prompt.
`;
}

function changelog(a: WizardAnswers): string {
  return `# Changelog

> Append-only. One entry per meaningful change. Never edit retroactively.

## ${today()} — project initialized

- Project \`${a.projectName}\` created via vibe-forge Setup Wizard
- Stack: ${a.stack}
- Testing tier: ${TDD_LABEL[a.tddTier]}
- Deployment target: ${a.deployment}
- Language: ${a.language}
- AI tools configured: ${a.tools.join(", ") || "none"}
`;
}

function projectMap(a: WizardAnswers): string {
  return `# Project map

> **Source of truth for AI agents.** Read this file first in every session.

## Project
- **Name:** ${a.projectName}
- **Description:** ${a.description}
- **Stack:** ${a.stack}
- **Language policy:** ${a.language}
- **TDD tier:** ${TDD_LABEL[a.tddTier]}
- **Deployment target:** ${a.deployment}
- **Audience:** ${a.audience}
- **AI tools:** ${a.tools.join(", ") || "none"}

## Key files

| File | Purpose | Update policy |
|------|---------|---------------|
| \`STATE.md\` | Current project state | Overwrite — current truth only |
| \`CHANGELOG.md\` | Linear history | Append only |
| \`PROJECT_MAP.md\` | This file — AI context anchor | Update on structural changes |
| \`PROJECT_RULES.md\` | Master rules | Update when rules change |
| \`CLIENT_DOCS.md\` | Non-technical docs | Update when behaviour changes |
| \`LESSONS.md\` | Mistakes and fix rules | Append after every correction |
| \`atomic-prompts/\` | Structured prompt library | Add files via /atomic-prompts skill |

## Source of truth
- Business logic → \`PROJECT_RULES.md\`
- Current state → \`STATE.md\`
- Feature history → \`CHANGELOG.md\`
- AI context → \`PROJECT_MAP.md\` (this file)
`;
}

function product(a: WizardAnswers): string {
  return `# Product definition

## What it is
${a.description}

## Who it serves
${a.audience}

## Core requirements
<!-- Fill in as requirements become clear during development -->
1. TBD — add your first requirement here
2. TBD
3. TBD

## Out of scope
<!-- Things this product explicitly does NOT do -->
- TBD

## Success criteria
<!-- How do you know when v1 is done? -->
- TBD
`;
}

function projectRules(a: WizardAnswers): string {
  return `# Project rules

> Master source of truth. Agent-agnostic. All tool-specific rule files derive from this.
> Last generated: ${today()} by vibe-forge Setup Wizard.

## Project identity
- **Name:** ${a.projectName}
- **Stack:** ${a.stack}
- **Language policy:** Code comments in English. Documentation in ${a.language}.
- **TDD tier:** ${TDD_LABEL[a.tddTier]}
- **Deployment target:** ${a.deployment}

## Security non-negotiables (cannot be overridden)
- NEVER commit \`.env\` files to git.
- ALWAYS use parameterised queries — no string concatenation in SQL/queries.
- Validate ALL user input at system boundaries before processing.
- No hardcoded API keys, passwords, or tokens in source code.
- All authentication routes must be rate-limited.
- Error messages shown to users must not leak internal state, stack traces, or secrets.

## Testing policy
${TDD_RULE[a.tddTier]}

## Code quality rules
- Functions: < 50 lines. Split if larger.
- Files: < 800 lines. Extract modules if larger.
- No deep nesting (> 4 levels) — use early returns.
- Prefer immutable operations — create new objects, do not mutate.
- No hardcoded magic numbers — use named constants.
- No \`console.log\` in production code — use a proper logger.

## Naming conventions
- Variables and functions: camelCase
- Classes, interfaces, types, components: PascalCase
- Constants: UPPER_SNAKE_CASE
- Booleans: \`is\` / \`has\` / \`should\` / \`can\` prefix
- Custom hooks: \`use\` prefix

## Error handling
- Handle errors explicitly at every level — never swallow silently.
- Provide user-friendly messages in UI-facing code.
- Log detailed context on the server side.

## Documentation rules
- \`STATE.md\`: overwrite to reflect current truth only. No history here.
- \`CHANGELOG.md\`: append only. Every meaningful change gets one entry.
- \`PROJECT_MAP.md\`: keep updated with every structural change.
- \`LESSONS.md\`: append after every mistake correction.
`;
}

function codingRules(a: WizardAnswers): string {
  return `# Coding rules

> Extends PROJECT_RULES.md with stack-specific guidance.

## Stack
${a.stack}

## General principles
- KISS — prefer the simplest solution that works.
- DRY — extract repeated logic; avoid copy-paste drift.
- YAGNI — don't build for hypothetical future requirements.

## Error handling
\`\`\`
// WRONG — silently swallowed
try { ... } catch {}

// CORRECT — explicit handling with context
try { ... } catch (error) {
  logger.error("Operation failed", { error, context });
  throw new Error("User-friendly message");
}
\`\`\`

## Input validation
- Use schema-based validation (Zod, Yup, Pydantic, etc.) at every system boundary.
- Never trust external data — API responses, user input, file content.
- Fail fast with a clear error message.

## Comments
- Only comment WHY — never WHAT.
- Delete commented-out code; use git history instead.
- No multi-line docstrings on obvious functions.
`;
}

function design(_a: WizardAnswers): string {
  return `# Design system

> Fill in as the UI takes shape. Start by defining colors and typography.

## Visual language
- **Style:** TBD — define after first UI prototype
- **Feel:** TBD (modern / minimal / playful / enterprise / …)

## Color palette
| Token | Value | Usage |
|-------|-------|-------|
| primary | TBD | Main actions, links |
| background | TBD | Page background |
| surface | TBD | Cards, panels |
| text | TBD | Body text |
| muted | TBD | Secondary text |
| border | TBD | Dividers, outlines |
| success | TBD | Positive states |
| warning | TBD | Caution states |
| danger | TBD | Error states |

## Typography
- **Body font:** TBD
- **Heading font:** TBD
- **Mono font:** TBD

## Components
Define reusable component patterns here as they emerge.

## Accessibility
- Minimum contrast ratio: 4.5:1 (WCAG AA)
- All interactive elements must be keyboard accessible
- Use semantic HTML elements
- Include ARIA labels for icon-only buttons

## Anti-patterns
- No Bootstrap/Material UI generic class patterns
- No cookie-cutter layouts from tutorials without customisation
`;
}

function clientDocs(a: WizardAnswers): string {
  return `# ${a.projectName} — project summary

> Plain-language summary. Safe to hand to a client or non-technical stakeholder at any time.

## What this does
${a.description}

## Who it is for
${a.audience}

## Current status
Project initialized. Development not yet started.

## What happens next
The development team will begin building the core features. Updates will be shared as milestones are reached.

## Contact
Contact the development team for progress updates, questions, or feedback.
`;
}

function releaseNotes(a: WizardAnswers): string {
  return `# Release notes

## v0.1.0 — ${today()}

### Project initialized
- Stack configured: ${a.stack}
- Testing tier: ${TDD_LABEL[a.tddTier]}
- Deployment target: ${a.deployment}

No features shipped yet. This entry marks project setup completion.
`;
}

function lessons(_a: WizardAnswers): string {
  return `# Lessons learned

> **Append after every mistake correction.**
> Format: What went wrong → Root cause → Preventive rule.
> Review at the start of each AI session.
>
> Entries "graduate" into PROJECT_RULES.md once they've proven durable.

<!-- No lessons yet — project just initialized. Add your first lesson here when something goes wrong and gets fixed. -->
`;
}

function deployment(a: WizardAnswers): string {
  return `# Deployment

## Target platform
${a.deployment}

## Environments
| Environment | URL | Notes |
|-------------|-----|-------|
| Development | localhost | Local dev server |
| Staging | TBD | Test before prod |
| Production | TBD | Live |

## Environment variables
<!-- Add all required environment variables here -->
| Variable | Description | Required | Where to get |
|----------|-------------|----------|-------------|
| TBD | TBD | Yes | TBD |

## Deploy steps
<!-- Fill in after confirming your deployment platform -->

### Staging
1. TBD

### Production
1. TBD

## Rollback procedure
1. TBD

## Post-deploy checks
- [ ] App loads without errors
- [ ] Authentication works
- [ ] Key user flows tested
- [ ] No secrets visible in logs
- [ ] Monitoring / alerting active
`;
}

function database(_a: WizardAnswers): string {
  return `# Database

> Fill in as the schema takes shape.

## Schema
<!-- Define tables / collections / models here as they are created -->

## Migration policy
- All schema changes go through versioned migrations
- Never modify production data directly
- Test migrations on a copy of prod data before applying

## Security
- Use parameterised queries only — no string concatenation
- Row-level security (RLS) where supported
- No direct database access from client-side code
- Sensitive fields (passwords, tokens) must be hashed, never stored plain

## Naming conventions
- Tables: plural snake_case (e.g., \`user_sessions\`)
- Columns: snake_case (e.g., \`created_at\`)
- Indices: \`idx_{table}_{column}\`
`;
}

function envExample(a: WizardAnswers): string {
  return `# ${a.projectName} — environment variables
# Copy this file to .env and fill in the values.
# NEVER commit .env to git.

# === Core ===
# NODE_ENV=development

# === Database ===
# DATABASE_URL=

# === Auth ===
# JWT_SECRET=
# SESSION_SECRET=

# === External services ===
# Add API keys and service URLs here as they become needed

# === Deployment ===
# PORT=3000
`;
}

function claudeMd(a: WizardAnswers): string {
  return `# Claude Code — ${a.projectName}

> Read \`PROJECT_MAP.md\` first. That is the canonical anchor for every session.

## Project
${a.description}

**Stack:** ${a.stack}
**TDD:** ${TDD_LABEL[a.tddTier]}
**Deployment:** ${a.deployment}

## Session start protocol
1. Read \`PROJECT_MAP.md\`
2. Read \`STATE.md\` for current work
3. Scan \`LESSONS.md\` for relevant patterns
4. Only then start coding

## Rules
Full rules in \`PROJECT_RULES.md\`. Key constraints:
- ${TDD_RULE[a.tddTier]}
- Never commit secrets or \`.env\` files
- Validate all user input at system boundaries
- Error handling must be explicit — never swallow silently

## Atomic prompts
Type \`/atomic-prompts\` to turn any one-line idea into a structured prompt file in \`atomic-prompts/\`.

## When updating code
1. Run tests before and after
2. Update \`STATE.md\` to reflect what changed
3. Append to \`CHANGELOG.md\`
4. Append to \`LESSONS.md\` if a mistake was corrected
`;
}

function cursorrules(a: WizardAnswers): string {
  return `# ${a.projectName} — Cursor rules

Read PROJECT_MAP.md first. That is the canonical context for every session.

## Project
${a.description}

Stack: ${a.stack}
TDD: ${TDD_LABEL[a.tddTier]}

## Rules
${TDD_RULE[a.tddTier]}
Never commit secrets or .env files.
Validate all user input at system boundaries.
Handle errors explicitly — never swallow silently.

## Session start
1. Read PROJECT_MAP.md
2. Read STATE.md
3. Scan LESSONS.md
4. Start working

## Atomic prompts
Use /atomic-prompts to turn any idea into a structured prompt file.
`;
}

function agentsMd(a: WizardAnswers): string {
  return `# ${a.projectName} — Codex agents

Read PROJECT_MAP.md first.

## Project
${a.description}

Stack: ${a.stack}
TDD: ${TDD_LABEL[a.tddTier]}

## Rules
${TDD_RULE[a.tddTier]}
Never commit .env or secrets. Validate all input. Explicit error handling.

## Session start
1. Read PROJECT_MAP.md  2. Read STATE.md  3. Scan LESSONS.md  4. Work
`;
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export function generateFiles(a: WizardAnswers): GeneratedFile[] {
  const files: GeneratedFile[] = [
    { path: "STATE.md", content: state(a) },
    { path: "CHANGELOG.md", content: changelog(a) },
    { path: "PROJECT_MAP.md", content: projectMap(a) },
    { path: "PRODUCT.md", content: product(a) },
    { path: "PROJECT_RULES.md", content: projectRules(a) },
    { path: "CODING_RULES.md", content: codingRules(a) },
    { path: "DESIGN.md", content: design(a) },
    { path: "CLIENT_DOCS.md", content: clientDocs(a) },
    { path: "RELEASE_NOTES.md", content: releaseNotes(a) },
    { path: "LESSONS.md", content: lessons(a) },
    { path: "DEPLOYMENT.md", content: deployment(a) },
    { path: "DATABASE.md", content: database(a) },
    { path: ".env.example", content: envExample(a) },
  ];

  if (a.tools.includes("claude-code")) {
    files.push({ path: "CLAUDE.md", content: claudeMd(a) });
  }
  if (a.tools.includes("cursor")) {
    files.push({ path: ".cursorrules", content: cursorrules(a) });
  }
  if (a.tools.includes("codex")) {
    files.push({ path: "AGENTS.md", content: agentsMd(a) });
  }

  return files;
}
